###############################################################################
# Makefile for creating lab applications
#
# Authors: Michael Steffen (steffma@iastate.edu)
# 	   Joseph Zambreno (zambreno@iastate.edu)
# 	   Iowa State University
###############################################################################
#
# Build script for a project
#
###############################################################################


# Executable name
EXECUTABLE := sierpinski

# C source files (separated by spaces)
CFILES := sierpinski.c
CPPFILES := 

# Additional include directories
INCLUDE_PATH := -I. 

# Additional link library directories
LIB_PATH := -L.

# Additional link libraries
#LIB := -lm

###############################################################################
# Rules and targets

include ../../../common/common.mk
