## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Sun Jul 25 04:22:59 PM CDT 2010
##
vlib work

# add libraries
vmap unisim /remote/Xilinx/12.2/ISE/vhdl/mti_se/6.5c/lin64/unisim 
vmap xilinxcorelib /remote/Xilinx/12.2/ISE/vhdl/mti_se/6.5c/lin64/xilinxcorelib

#Compile files in misc folder (excluding model parameter file)#
#vlog  ../hdl/misc/*.v
vcom  ../hdl/misc/*.vhd
#vcom  ../hdl/misc/vbios_brom/*.vhd

#Compile ethernet files
vcom   ../hdl/ethernet/*.vhd
vcom   ../hdl/ethernet/physical/*.vhd
vcom   ../hdl/ethernet/client/*.vhd
vcom   ../hdl/ethernet/client/fifo/*.vhd

#Compile files in disp folder (excluding model parameter file)#
vlog  ../hdl/disp/*.v
vcom  ../hdl/disp/*.vhd
vcom  ../hdl/disp/fblinec/*.vhd

#Compile files for bus_interface
vcom    ../hdl/bus/*.vhd
vcom   ../hdl/bus/bus_instruction_fifo/*.vhd

#Compile files in uart folder (excluding model parameter file)#
vlog  ../hdl/uart/*.v
vcom  ../hdl/uart/*.vhd
vcom  ../hdl/uart/fifo/*.vhd

#Compile files in user folder (excluding model parameter file)#
#vlog  ../hdl/user/*.v
vcom  ../hdl/user/*.vhd
vcom  ../hdl/user/user_cmd_fifo/*.vhd
vcom  ../hdl/user/user_read_fifo/*.vhd
vcom  ../hdl/user/cache/*.vhd
vcom  ../hdl/user/cache/BRAM_Data/*.vhd
vcom  ../hdl/user/cache/tag_data/*.vhd
vcom  ../hdl/user/queue_bram/*.vhd
vcom  ../hdl/user/multiplyer/*.vhd

#Compile all modules#
#vlog  ../hdl/ddr2/*.v
vcom  ../hdl/ddr2/*.vhd
vcom  ../hdl/ddr2/addr_fifo/*.vhd
vcom  ../hdl/ddr2/data_fifo/*.vhd

vcom  ../hdl/SGP.vhd

#Compile files in sim folder (excluding model parameter file)#
vlog  ../sim/*.v
vcom  ../sim/*.vhd

#Pass the parameters for memory model parameter file#
vlog  +incdir+. +define+x512Mb +define+sg37E +define+x16 ../sim/ddr2_model.v

#Load the design. Use required libraries.#
vsim -t ps -novopt +notimingchecks -L unisim work.tb_SGP glbl

onerror {resume}
#Log all the objects in design. These will appear in .wlf file#
log -r /*
#do wave_sim_fast.do
#force -freeze sim:/tb_sgp/uut_sgp/u_disp_interface/tft_cont/TFT_IF_U5/gen_dvi_if/iic_init/Done 1 0

#Change radix to Hexadecimal#
radix hex
#Supress Numeric Std package and Arith package warnings.#
#For VHDL designs we get some warnings due to unknown values on some signals at startup#
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0#
#We may also get some Arithmetic packeage warnings because of unknown values on#
#some of the signals that are used in an Arithmetic operation.#
#In order to suppress these warnings, we use following two commands#
set NumericStdNoWarnings 1
set StdArithNoWarnings 1


#Choose simulation run time by inserting a breakpoint and then run for specified #
#period. For more details, refer to Simulation Guide section of MIG user guide (UG086).#
when {/tb_SGP/uut_SGP/ddr2_done = 1} {
if {[when -label a_100] == ""} {
when -label a_100 { $now = 40 ms } {
nowhen a_100
report simulator control
report simulator state
}
}
}


#In case calibration fails to complete, choose the run time and then stop#
when {$now = @500 us and /tb_SGP/uut_SGP/ddr2_done != 1} {
echo "TEST FAILED: CALIBRATION DID NOT COMPLETE"
stop
}
force -freeze sim:/tb_sgp/uut_sgp/u_mem_init/init_done 1 0
force -freeze sim:/tb_sgp/uut_sgp/u_disp_interface/tft_cont/TFT_IF_U5/gen_dvi_if/iic_init/Done 0 0
#run 100ns
#add wave sim:/tb_sgp/uut_sgp/u_user_interface/u_user_logic/*
#add wave sim:/tb_sgp/uut_sgp/u_user_interface/*
#add wave sim:/tb_sgp/uut_sgp/u_mem_arbiter/*
#add wave sim:/tb_sgp/uut_sgp/u_user_interface/*
#add wave sim:/tb_sgp/uut_sgp/u_user_interface/u_user_logic/host_u/*
#run 310ns
force -freeze sim:/tb_sgp/uut_sgp/u_disp_interface/tft_cont/TFT_IF_U5/gen_dvi_if/iic_init/Done 1 0

#do pipe2d_wave.do 

run 400ns
#force -freeze sim:/tb_sgp/uut_sgp/u_user_interface/u_user_logic/host_u/host_busfeedback(2).full 1 0
#run 83000ns
#noforce sim:/tb_sgp/uut_sgp/u_user_interface/u_user_logic/host_u/host_busfeedback(2).full
#add wave sim:/tb_sgp/uut_sgp/u_user_interface/u_user_logic/host_u/*
#run 100ns

#run -all
stop

